/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_me_patch"];
        trace?: never;
    };
    "/profiles/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_profiles__handle__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Progress */
        get: operations["read_progress_me_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Activity */
        get: operations["read_activity_me_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/league": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read League */
        get: operations["read_league_me_league_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/streak/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Use Streak Freeze */
        post: operations["use_streak_freeze_me_streak_freeze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roadmaps */
        get: operations["list_roadmaps_roadmaps_get"];
        put?: never;
        /** Create Roadmap */
        post: operations["create_roadmap_roadmaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Roadmap */
        get: operations["read_roadmap_roadmaps__roadmap_id__get"];
        put?: never;
        post?: never;
        /** Archive Roadmap */
        delete: operations["archive_roadmap_roadmaps__roadmap_id__delete"];
        options?: never;
        head?: never;
        /** Update Roadmap */
        patch: operations["update_roadmap_roadmaps__roadmap_id__patch"];
        trace?: never;
    };
    "/steps/{step_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Step */
        get: operations["read_step_steps__step_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/steps/{step_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Step */
        post: operations["complete_step_steps__step_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse Listings */
        get: operations["browse_listings_marketplace_listings_get"];
        put?: never;
        /** Publish Listing */
        post: operations["publish_listing_marketplace_listings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Listing */
        get: operations["read_listing_marketplace_listings__listing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Listing */
        patch: operations["update_listing_marketplace_listings__listing_id__patch"];
        trace?: never;
    };
    "/marketplace/listings/{listing_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Version */
        post: operations["publish_version_marketplace_listings__listing_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings/{listing_id}/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install Listing */
        post: operations["install_listing_marketplace_listings__listing_id__install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/listings/{listing_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Review Listing */
        put: operations["review_listing_marketplace_listings__listing_id__review_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/roadmap-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Roadmap Draft */
        post: operations["start_roadmap_draft_ai_roadmap_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/roadmap-drafts/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Roadmap Draft */
        get: operations["read_roadmap_draft_ai_roadmap_drafts__run_id__get"];
        put?: never;
        post?: never;
        /** Cancel Roadmap Draft */
        delete: operations["cancel_roadmap_draft_ai_roadmap_drafts__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/step-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Step Suggestions */
        post: operations["create_step_suggestions_ai_step_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Author */
        Author: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Handle */
            handle: string | null;
            /** Display Name */
            display_name: string | null;
        };
        /** CheckExercise */
        CheckExercise: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "check";
            /** Prompt */
            prompt: string;
        };
        /** CompletionOut */
        CompletionOut: {
            /** Xp Awarded */
            xp_awarded: number;
            /** Total Xp */
            total_xp: number;
            level: components["schemas"]["LevelInfo"];
            streak: components["schemas"]["StreakOut"];
            /** Quests Completed */
            quests_completed: components["schemas"]["QuestOut"][];
        };
        /** DayXp */
        DayXp: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Xp */
            xp: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Handle */
            handle: string | null;
            /** Display Name */
            display_name: string | null;
            /** Xp */
            xp: number;
        };
        /** LeagueEntry */
        LeagueEntry: {
            /** Rank */
            rank: number;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Handle */
            handle: string | null;
            /** Display Name */
            display_name: string | null;
            /** Xp */
            xp: number;
        };
        /** LeagueOut */
        LeagueOut: {
            /** Tier */
            tier: number;
            /** Tier Name */
            tier_name: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Promote */
            promote: number;
            /** Demote */
            demote: number;
            /** Entries */
            entries: components["schemas"]["LeagueEntry"][];
            me: components["schemas"]["LeagueEntry"] | null;
        };
        /** LevelInfo */
        LevelInfo: {
            /** Level */
            level: number;
            /** Title */
            title: string;
            /** Into Level */
            into_level: number;
            /** Span */
            span: number;
        };
        /** ListingDetail */
        ListingDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            author: components["schemas"]["Author"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "course" | "habit";
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Category
             * @enum {string}
             */
            category: "fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom";
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "unlisted" | "removed";
            /** Is Official */
            is_official: boolean;
            /** Latest Version */
            latest_version: number;
            /** Installs */
            installs: number;
            /** Rating Avg */
            rating_avg: number;
            /** Rating Count */
            rating_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            content: components["schemas"]["RoadmapDraft-Output"];
            /** Leaderboard */
            leaderboard: components["schemas"]["LeaderboardEntry"][];
        };
        /** ListingOut */
        ListingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            author: components["schemas"]["Author"];
            /**
             * Kind
             * @enum {string}
             */
            kind: "course" | "habit";
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Category
             * @enum {string}
             */
            category: "fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom";
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "published" | "unlisted" | "removed";
            /** Is Official */
            is_official: boolean;
            /** Latest Version */
            latest_version: number;
            /** Installs */
            installs: number;
            /** Rating Avg */
            rating_avg: number;
            /** Rating Count */
            rating_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ListingUpdate */
        ListingUpdate: {
            /** Status */
            status?: ("draft" | "published" | "unlisted" | "removed") | null;
            /** Is Official */
            is_official?: boolean | null;
        };
        /** NextStep */
        NextStep: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Minutes */
            minutes: number;
            /** Xp */
            xp: number;
            /** Done */
            done: boolean;
            /** Unit Position */
            unit_position: number;
            /** Unit Title */
            unit_title: string;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Handle */
            handle: string | null;
            /** Display Name */
            display_name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Interests */
            interests: ("fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom")[];
            /** Daily Xp Goal */
            daily_xp_goal: number;
            /** Reminder Time */
            reminder_time: string | null;
            /** Timezone */
            timezone: string;
            /**
             * Plan
             * @enum {string}
             */
            plan: "free" | "plus";
            /** League Opt In */
            league_opt_in: boolean;
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Handle */
            handle?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Interests */
            interests?: ("fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom")[] | null;
            /** Daily Xp Goal */
            daily_xp_goal?: number | null;
            /** Reminder Time */
            reminder_time?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** League Opt In */
            league_opt_in?: boolean | null;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Total Xp */
            total_xp: number;
            level: components["schemas"]["LevelInfo"];
            streak: components["schemas"]["StreakOut"];
            /** Today Xp */
            today_xp: number;
            /** Daily Xp Goal */
            daily_xp_goal: number;
            /** Quests */
            quests: components["schemas"]["QuestOut"][];
        };
        /** PublicProfile */
        PublicProfile: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Handle */
            handle: string | null;
            /** Display Name */
            display_name: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PublishRequest */
        PublishRequest: {
            /**
             * Roadmap Id
             * Format: uuid
             */
            roadmap_id: string;
            /**
             * Status
             * @default published
             * @enum {string}
             */
            status: "draft" | "published" | "unlisted";
        };
        /** QuestOut */
        QuestOut: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Xp */
            xp: number;
            /** Progress */
            progress: number;
            /** Target */
            target: number;
            /** Done */
            done: boolean;
        };
        /** QuizExercise */
        QuizExercise: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "quiz";
            /** Prompt */
            prompt: string;
            /** Options */
            options: string[];
            /** Answer */
            answer: number;
        };
        /** ReviewIn */
        ReviewIn: {
            /** Rating */
            rating: number;
            /** Body */
            body?: string | null;
        };
        /** ReviewOut */
        ReviewOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Listing Id
             * Format: uuid
             */
            listing_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Rating */
            rating: number;
            /** Body */
            body: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RoadmapBrief */
        RoadmapBrief: {
            /** Goal */
            goal: string;
            /**
             * Weeks
             * @default 12
             */
            weeks: number;
            /**
             * Minutes Per Day
             * @default 15
             */
            minutes_per_day: number;
            /**
             * Level
             * @default beginner
             * @enum {string}
             */
            level: "beginner" | "some" | "solid";
            /**
             * Context
             * @default
             */
            context: string;
        };
        /** RoadmapDraft */
        "RoadmapDraft-Input": {
            /**
             * Kind
             * @enum {string}
             */
            kind: "course" | "habit";
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Category
             * @default custom
             * @enum {string}
             */
            category: "fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom";
            /**
             * Level
             * @default beginner
             * @enum {string}
             */
            level: "beginner" | "some" | "solid";
            /** Units */
            units: components["schemas"]["UnitDraft-Input"][];
        };
        /** RoadmapDraft */
        "RoadmapDraft-Output": {
            /**
             * Kind
             * @enum {string}
             */
            kind: "course" | "habit";
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Category
             * @default custom
             * @enum {string}
             */
            category: "fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom";
            /**
             * Level
             * @default beginner
             * @enum {string}
             */
            level: "beginner" | "some" | "solid";
            /** Units */
            units: components["schemas"]["UnitDraft-Output"][];
            /** Total Xp */
            readonly total_xp: number;
        };
        /** RoadmapDraftRun */
        RoadmapDraftRun: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "cancelled";
            /** Stage */
            stage: string | null;
            draft: components["schemas"]["RoadmapDraft-Output"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RoadmapOut */
        RoadmapOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "course" | "habit";
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Category
             * @enum {string}
             */
            category: "fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom";
            /**
             * Level
             * @enum {string}
             */
            level: "beginner" | "some" | "solid";
            /** Source Listing Id */
            source_listing_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Unit Count */
            unit_count: number;
            /** Total Steps */
            total_steps: number;
            /** Done Steps */
            done_steps: number;
            next_step: components["schemas"]["NextStep"] | null;
            /** Units */
            units: components["schemas"]["UnitOut"][];
        };
        /** RoadmapSummary */
        RoadmapSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "course" | "habit";
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Category
             * @enum {string}
             */
            category: "fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom";
            /**
             * Level
             * @enum {string}
             */
            level: "beginner" | "some" | "solid";
            /** Source Listing Id */
            source_listing_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Unit Count */
            unit_count: number;
            /** Total Steps */
            total_steps: number;
            /** Done Steps */
            done_steps: number;
            next_step: components["schemas"]["NextStep"] | null;
        };
        /** RoadmapUpdate */
        RoadmapUpdate: {
            /** Title */
            title?: string | null;
            /** Summary */
            summary?: string | null;
            /** Category */
            category?: ("fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom") | null;
        };
        /** StepDetail */
        StepDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Minutes */
            minutes: number;
            /** Xp */
            xp: number;
            /**
             * Roadmap Id
             * Format: uuid
             */
            roadmap_id: string;
            /** Exercises */
            exercises: (components["schemas"]["QuizExercise"] | components["schemas"]["CheckExercise"] | components["schemas"]["TimerExercise"])[];
        };
        /** StepDraft */
        "StepDraft-Input": {
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Minutes */
            minutes: number;
            /** Exercises */
            exercises?: (components["schemas"]["QuizExercise"] | components["schemas"]["CheckExercise"] | components["schemas"]["TimerExercise"])[];
        };
        /** StepDraft */
        "StepDraft-Output": {
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Minutes */
            minutes: number;
            /** Exercises */
            exercises?: (components["schemas"]["QuizExercise"] | components["schemas"]["CheckExercise"] | components["schemas"]["TimerExercise"])[];
            /** Xp */
            readonly xp: number;
        };
        /** StepOut */
        StepOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Minutes */
            minutes: number;
            /** Xp */
            xp: number;
            /** Done */
            done: boolean;
        };
        /** StepSuggestionRequest */
        StepSuggestionRequest: {
            /** Title */
            title: string;
            /** Existing Steps */
            existing_steps?: string[];
            /**
             * Count
             * @default 3
             */
            count: number;
        };
        /** StepSuggestions */
        StepSuggestions: {
            /** Steps */
            steps: components["schemas"]["StepDraft-Output"][];
        };
        /** StreakOut */
        StreakOut: {
            /** Current */
            current: number;
            /** Longest */
            longest: number;
            /** Freezes */
            freezes: number;
            /** Active Today */
            active_today: boolean;
            /** At Risk */
            at_risk: boolean;
        };
        /** TimerExercise */
        TimerExercise: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "timer";
            /** Prompt */
            prompt: string;
            /** Minutes */
            minutes: number;
        };
        /** UnitDraft */
        "UnitDraft-Input": {
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Steps */
            steps: components["schemas"]["StepDraft-Input"][];
        };
        /** UnitDraft */
        "UnitDraft-Output": {
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Steps */
            steps: components["schemas"]["StepDraft-Output"][];
        };
        /** UnitOut */
        UnitOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    update_me_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_profiles__handle__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_progress_me_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
        };
    };
    read_activity_me_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayXp"][];
                };
            };
        };
    };
    read_league_me_league_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueOut"];
                };
            };
        };
    };
    use_streak_freeze_me_streak_freeze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakOut"];
                };
            };
        };
    };
    list_roadmaps_roadmaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapSummary"][];
                };
            };
        };
    };
    create_roadmap_roadmaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapDraft-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_roadmap_roadmaps__roadmap_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_roadmap_roadmaps__roadmap_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_roadmap_roadmaps__roadmap_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_step_steps__step_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_step_steps__step_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_listings_marketplace_listings_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: ("fitness" | "languages" | "music" | "coding" | "reading" | "mindfulness" | "finance" | "cooking" | "career" | "art" | "custom") | null;
                kind?: ("course" | "habit") | null;
                official?: boolean | null;
                sort?: "top_week" | "rating" | "new";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_listing_marketplace_listings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_listing_marketplace_listings__listing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_listing_marketplace_listings__listing_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_version_marketplace_listings__listing_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_listing_marketplace_listings__listing_id__install_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_listing_marketplace_listings__listing_id__review_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_roadmap_draft_ai_roadmap_drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapBrief"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapDraftRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_roadmap_draft_ai_roadmap_drafts__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapDraftRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_roadmap_draft_ai_roadmap_drafts__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_step_suggestions_ai_step_suggestions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepSuggestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepSuggestions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
